version: 2

jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: install-test-suite
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: npm run build